exports.getConfirmBooking = function(bookingDetails, bookingId) {

	console.log("date & time :"+bookingDetails.pickupdatetime);
	var mailOptions="";
	//mailOptions += "<!DOCTYPE HTML PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional \/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\"><html><head><title><\/title><meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=320, target-densitydpi=device-dpi\"> <style type=\"text\/css\"> \/* Mobile-specific Styles *\/ @media only screen and (max-width: 660px) { table[class=w0], td[class=w0] { width: 0 !important; } table[class=w10], td[class=w10], img[class=w10] { width:10px !important; } table[class=w15], td[class=w15], img[class=w15] { width:5px !important; } table[class=w30], td[class=w30], img[class=w30] { width:10px !important; } table[class=w60], td[class=w60], img[class=w60] { width:10px !important; } table[class=w125], td[class=w125], img[class=w125] { width:80px !important; } table[class=w130], td[class=w130], img[class=w130] { width:55px !important; } table[class=w140], td[class=w140], img[class=w140] { width:90px !important; } table[class=w160], td[class=w160], img[class=w160] { width:180px !important; } table[class=w170], td[class=w170], img[class=w170] { width:100px !important; } table[class=w180], td[class=w180], img[class=w180] { width:80px !important; } table[class=w195], td[class=w195], img[class=w195] { width:80px !important; } table[class=w220], td[class=w220], img[class=w220] { width:80px !important; } table[class=w240], td[class=w240], img[class=w240] { width:180px !important; } table[class=w255], td[class=w255], img[class=w255] { width:185px !important; } table[class=w275], td[class=w275], img[class=w275] { width:135px !important; } table[class=w280], td[class=w280], img[class=w280] { width:135px !important; } table[class=w300], td[class=w300], img[class=w300] { width:140px !important; } table[class=w325], td[class=w325], img[class=w325] { width:95px !important; } table[class=w360], td[class=w360], img[class=w360] { width:140px !important; } table[class=w410], td[class=w410], img[class=w410] { width:180px !important; } table[class=w470], td[class=w470], img[class=w470] { width:200px !important; } table[class=w580], td[class=w580], img[class=w580] { width:280px !important; } table[class=w640], td[class=w640], img[class=w640] { width:300px !important; } table[class*=hide], td[class*=hide], img[class*=hide], p[class*=hide], span[class*=hide] { display:none !important; } table[class=h0], td[class=h0] { height: 0 !important; } p[class=footer-content-left] { text-align: center !important; } #headline p { font-size: 30px !important; } .article-content, #left-sidebar{ -webkit-text-size-adjust: 90% !important; -ms-text-size-adjust: 90% !important; } .header-content, .footer-content-left {-webkit-text-size-adjust: 80% !important; -ms-text-size-adjust: 80% !important;} img { height: auto; line-height: 100%;}  } \/* Client-specific Styles *\/ #outlook a { padding: 0; }	\/* Force Outlook to provide a \"view in browser\" button. *\/ body { width: 100% !important; } .ReadMsgBody { width: 100%; } .ExternalClass { width: 100%; display:block !important; } \/* Force Hotmail to display emails at full width *\/ \/* Reset Styles *\/ \/* Add 100px so mobile switch bar doesn't cover street address. *\/ body { background-color: #ececec; margin: 0; padding: 0; } img { outline: none; text-decoration: none; display: block;} br, strong br, b br, em br, i br { line-height:100%; } h1, h2, h3, h4, h5, h6 { line-height: 100% !important; -webkit-font-smoothing: antialiased; } h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; } h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {	color: red !important; } \/* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. *\/ h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; } \/* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. *\/  table td, table tr { border-collapse: collapse; } .yshortcuts, .yshortcuts a, .yshortcuts a:link,.yshortcuts a:visited, .yshortcuts a:hover, .yshortcuts a span { color: black; text-decoration: none !important; border-bottom: none !important; background: none !important; }	\/* Body text color for the New Yahoo.  This example sets the font of Yahoo's Shortcuts to black. *\/ \/* This most probably won't work in all email clients. Don't include code blocks in email. *\/ code {   white-space: normal;   word-break: break-all; } #background-table { background-color: #ececec; } \/* Webkit Elements *\/ #top-bar { border-radius:6px 6px 0px 0px; -moz-border-radius: 6px 6px 0px 0px; -webkit-border-radius:6px 6px 0px 0px; -webkit-font-smoothing: antialiased; background-color: #7e8485; color: #e7cba3; } #top-bar a { font-weight: bold; color: #e7cba3; text-decoration: none;} #footer { border-radius:0px 0px 6px 6px; -moz-border-radius: 0px 0px 6px 6px; -webkit-border-radius:0px 0px 6px 6px; -webkit-font-smoothing: antialiased; } \/* Fonts and Content *\/ body, td { font-family: HelveticaNeue, sans-serif; } .header-content, .footer-content-left, .footer-content-right { -webkit-text-size-adjust: none; -ms-text-size-adjust: none; } \/* Prevent Webkit and Windows Mobile platforms from changing default font sizes on header and footer. *\/ .header-content { font-size: 12px; color: #e7cba3; } .header-content a { font-weight: bold; color: #e7cba3; text-decoration: none; } #headline p { color: #e7cba3; font-family: HelveticaNeue, sans-serif; font-size: 36px; text-align: center; margin-top:0px; margin-bottom:30px; } #headline p a { color: #e7cba3; text-decoration: none; } .article-title { font-size: 18px; line-height:24px; color: #9a9661; font-weight:bold; margin-top:0px; margin-bottom:18px; font-family: HelveticaNeue, sans-serif; } .article-title a { color: #9a9661; text-decoration: none; } .article-title.with-meta {margin-bottom: 0;} .article-meta { font-size: 13px; line-height: 20px; color: #ccc; font-weight: bold; margin-top: 0;} .article-content { font-size: 13px; line-height: 18px; color: #444444; margin-top: 0px; margin-bottom: 18px; font-family: HelveticaNeue, sans-serif; } .article-content a { color: #00707b; font-weight:bold; text-decoration:none; } .article-content img { max-width: 100% } .article-content ol, .article-content ul { margin-top:0px; margin-bottom:18px; margin-left:19px; padding:0; } .article-content li { font-size: 13px; line-height: 18px; color: #444444; } .article-content li a { color: #00707b; text-decoration:underline; } .article-content p {margin-bottom: 15px;} .footer-content-left { font-size: 12px; line-height: 15px; color: #e2e2e2; margin-top: 0px; margin-bottom: 15px; } .footer-content-left a { color: #e7cba3; font-weight: bold; text-decoration: none; } .footer-content-right { font-size: 11px; line-height: 16px; color: #e2e2e2; margin-top: 0px; margin-bottom: 15px; } .footer-content-right a { color: #e7cba3; font-weight: bold; text-decoration: none; } #footer { background-color: #000000; color: #e2e2e2; } #footer a { color: #e7cba3; text-decoration: none; font-weight: bold; } #permission-reminder { white-space: normal; } #street-address { color: #e7cba3; white-space: normal; } <\/style> <!--[if gte mso 9]> <style _tmplitem=\"2480\" > .article-content ol, .article-content ul {    margin: 0 0 0 24px;    padding: 0;    list-style-position: inside; } <\/style> <![endif]--><\/head><body><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"background-table\"> 	<tbody><tr> 		<td align=\"center\" bgcolor=\"#ececec\">         	<table class=\"w640\" style=\"margin:0 10px;\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">             	<tbody><tr><td class=\"w640\" width=\"640\" height=\"20\"><\/td><\/tr>                             	<tr>                 	<td class=\"w640\" width=\"640\">                         <table id=\"top-bar\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" bgcolor=\"#242424\">     <tbody><tr>         <td class=\"w15\" width=\"15\"><\/td>         <td class=\"w325\" width=\"350\" valign=\"middle\" align=\"left\">             <table class=\"w325\" width=\"350\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                 <tbody><tr><td class=\"w325\" width=\"350\" height=\"8\"><\/td><\/tr>             <\/tbody><\/table>             <div class=\"header-content\">Team<\/div>             <table class=\"w325\" width=\"350\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                 <tbody><tr><td class=\"w325\" width=\"350\" height=\"8\"><\/td><\/tr>             <\/tbody><\/table>         <\/td>         <td class=\"w30\" width=\"30\"><\/td>         <td class=\"w255\" width=\"255\" valign=\"middle\" align=\"right\">             <table class=\"w255\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                 <tbody><tr><td class=\"w255\" width=\"255\" height=\"8\"><\/td><\/tr>             <\/tbody><\/table>             <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">     <tbody><tr>                    <\/tr> <\/tbody><\/table>             <table class=\"w255\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                 <tbody><tr><td class=\"w255\" width=\"255\" height=\"8\"><\/td><\/tr>             <\/tbody><\/table>         <\/td>         <td class=\"w15\" width=\"15\"><\/td>     <\/tr> <\/tbody><\/table>                                             <\/td>                 <\/tr>                 <tr>                 <td id=\"header\" class=\"w640\" width=\"640\" align=\"center\" bgcolor=\"#242424\">         <table class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">         <tbody><tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580\" width=\"580\" height=\"30\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>         <tr>             <td class=\"w30\" width=\"30\"><\/td>             <td class=\"w580\" width=\"580\">                 <div align=\"center\" id=\"headline\">                     <p>                         <strong><singleline label=\"Title\">Booking Confirmation<\/singleline><\/strong>                     <\/p>                 <\/div>             <\/td>             <td class=\"w30\" width=\"30\"><\/td>         <\/tr>     <\/tbody><\/table>         <\/td>                 <\/tr>                                 <tr><td class=\"w640\" width=\"640\" height=\"30\" bgcolor=\"#ffffff\"><\/td><\/tr>                 <tr id=\"simple-content-row\"><td class=\"w640\" width=\"640\" bgcolor=\"#ffffff\">     <table align=\"left\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">         <tbody><tr>             <td class=\"w30\" width=\"30\"><\/td>             <td class=\"w580\" width=\"580\">                 <repeater>                                         <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Pickup Address<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.pickup+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">DropOff Address<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.dropoff+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Date & Time<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.pickupdatetime+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout>                                					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">No Of Passengers<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.passengers+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Name<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.name+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Name<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">Enter your description<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Email Id<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.emailid+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Phone Number<\/singleline><\/p>                                     <div align=\"left\" class=\"article-content\">                                         <multiline label=\"Description\">"+bookingDetails.phone+"<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout> 					 					 <layout label=\"Text only\">                         <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">                             <tbody><tr>                                 <td class=\"w580\" width=\"580\">                                     <p align=\"right\" class=\"article-title\" style=\"color:black;\"><singleline label=\"Title\">Enjoy Your Ride!!!<\/singleline><\/p>                                     <div align=\"right\" class=\"article-content\">                                         <multiline label=\"Description\">Thanks for your Booking<\/multiline>                                     <\/div>                                 <\/td>                             <\/tr>                             <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>                         <\/tbody><\/table>                     <\/layout>                                    <\/repeater>             <\/td>             <td class=\"w30\" width=\"30\"><\/td>         <\/tr>     <\/tbody><\/table> <\/td><\/tr>                 <tr><td class=\"w640\" width=\"640\" height=\"15\" bgcolor=\"#ffffff\"><\/td><\/tr>                                 <tr>                 <td class=\"w640\" width=\"640\">     <table id=\"footer\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" bgcolor=\"#000000\">         <tbody><tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580 h0\" width=\"360\" height=\"30\"><\/td><td class=\"w0\" width=\"60\"><\/td><td class=\"w0\" width=\"160\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>         <tr>             <td class=\"w30\" width=\"30\"><\/td>             <td class=\"w580\" width=\"360\" valign=\"top\">             <span class=\"hide\"><p id=\"permission-reminder\" align=\"left\" class=\"footer-content-left\"><\/p><\/span>             <p align=\"left\" class=\"footer-content-left\">Team Name<\/p>             <\/td>             <td class=\"hide w0\" width=\"60\"><\/td>             <td class=\"hide w0\" width=\"160\" valign=\"top\">             <p id=\"street-address\" align=\"right\" class=\"footer-content-right\"><\/p>             <\/td>             <td class=\"w30\" width=\"30\"><\/td>         <\/tr>         <tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580 h0\" width=\"360\" height=\"15\"><\/td><td class=\"w0\" width=\"60\"><\/td><td class=\"w0\" width=\"160\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>     <\/tbody><\/table> <\/td>                 <\/tr>                 <tr><td class=\"w640\" width=\"640\" height=\"60\"><\/td><\/tr>             <\/tbody><\/table>         <\/td> 	<\/tr> <\/tbody><\/table><\/body><\/html> ";
	
	var mailOptions="";
	mailOptions += "<!DOCTYPE HTML PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional \/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\"><html><head><title><\/title><meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=320, target-densitydpi=device-dpi\">";
	mailOptions += "<style type=\"text\/css\">";
	mailOptions += "\/* Mobile-specific Styles *\/";
	mailOptions += "@media only screen and (max-width: 660px) { ";
	mailOptions += "table[class=w0], td[class=w0] { width: 0 !important; }";
	mailOptions += "table[class=w10], td[class=w10], img[class=w10] { width:10px !important; }";
	mailOptions += "table[class=w15], td[class=w15], img[class=w15] { width:5px !important; }";
	mailOptions += "table[class=w30], td[class=w30], img[class=w30] { width:10px !important; }";
	mailOptions += "table[class=w60], td[class=w60], img[class=w60] { width:10px !important; }";
	mailOptions += "table[class=w125], td[class=w125], img[class=w125] { width:80px !important; }";
	mailOptions += "table[class=w130], td[class=w130], img[class=w130] { width:55px !important; }";
	mailOptions += "table[class=w140], td[class=w140], img[class=w140] { width:90px !important; }";
	mailOptions += "table[class=w160], td[class=w160], img[class=w160] { width:180px !important; }";
	mailOptions += "table[class=w170], td[class=w170], img[class=w170] { width:100px !important; }";
	mailOptions += "table[class=w180], td[class=w180], img[class=w180] { width:80px !important; }";
	mailOptions += "table[class=w195], td[class=w195], img[class=w195] { width:80px !important; }";
	mailOptions += "table[class=w220], td[class=w220], img[class=w220] { width:80px !important; }";
	mailOptions += "table[class=w240], td[class=w240], img[class=w240] { width:180px !important; }";
	mailOptions += "table[class=w255], td[class=w255], img[class=w255] { width:185px !important; }";
	mailOptions += "table[class=w275], td[class=w275], img[class=w275] { width:135px !important; }";
	mailOptions += "table[class=w280], td[class=w280], img[class=w280] { width:135px !important; }";
	mailOptions += "table[class=w300], td[class=w300], img[class=w300] { width:140px !important; }";
	mailOptions += "table[class=w325], td[class=w325], img[class=w325] { width:95px !important; }";
	mailOptions += "table[class=w360], td[class=w360], img[class=w360] { width:140px !important; }";
	mailOptions += "table[class=w410], td[class=w410], img[class=w410] { width:180px !important; }";
	mailOptions += "table[class=w470], td[class=w470], img[class=w470] { width:200px !important; }";
	mailOptions += "table[class=w580], td[class=w580], img[class=w580] { width:280px !important; }";
	mailOptions += "table[class=w640], td[class=w640], img[class=w640] { width:300px !important; }";
	mailOptions += "table[class*=hide], td[class*=hide], img[class*=hide], p[class*=hide], span[class*=hide] { display:none !important; }";
	mailOptions += "table[class=h0], td[class=h0] { height: 0 !important; }";
	mailOptions += "p[class=footer-content-left] { text-align: center !important; }";
	mailOptions += "#headline p { font-size: 30px !important; }";
	mailOptions += ".article-content, #left-sidebar{ -webkit-text-size-adjust: 90% !important; -ms-text-size-adjust: 90% !important; }";
	mailOptions += ".header-content, .footer-content-left {-webkit-text-size-adjust: 80% !important; -ms-text-size-adjust: 80% !important;}";
	mailOptions += "img { height: auto; line-height: 100%;}";
	mailOptions += " } ";
	mailOptions += "\/* Client-specific Styles *\/";
	mailOptions += "#outlook a { padding: 0; }	\/* Force Outlook to provide a \"view in browser\" button. *\/";
	mailOptions += "body { width: 100% !important; }";
	mailOptions += ".ReadMsgBody { width: 100%; }";
	mailOptions += ".ExternalClass { width: 100%; display:block !important; } \/* Force Hotmail to display emails at full width *\/";
	mailOptions += "\/* Reset Styles *\/";
	mailOptions += "\/* Add 100px so mobile switch bar doesn't cover street address. *\/";
	mailOptions += "body { background-color: #ececec; margin: 0; padding: 0; }";
	mailOptions += "img { outline: none; text-decoration: none; display: block;}";
	mailOptions += "br, strong br, b br, em br, i br { line-height:100%; }";
	mailOptions += "h1, h2, h3, h4, h5, h6 { line-height: 100% !important; -webkit-font-smoothing: antialiased; }";
	mailOptions += "h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; }";
	mailOptions += "h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {	color: red !important; }";
	mailOptions += "\/* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. *\/";
	mailOptions += "h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; }";
	mailOptions += "\/* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. *\/  ";
	mailOptions += "table td, table tr { border-collapse: collapse; }";
	mailOptions += ".yshortcuts, .yshortcuts a, .yshortcuts a:link,.yshortcuts a:visited, .yshortcuts a:hover, .yshortcuts a span {";
	mailOptions += "color: black; text-decoration: none !important; border-bottom: none !important; background: none !important;";
	mailOptions += "}	\/* Body text color for the New Yahoo.  This example sets the font of Yahoo's Shortcuts to black. *\/";
	mailOptions += "\/* This most probably won't work in all email clients. Don't include code blocks in email. *\/";
	mailOptions += "code {";
	mailOptions += "  white-space: normal;";
	mailOptions += "  word-break: break-all;";
	mailOptions += "}";
	mailOptions += "#background-table { background-color: #ececec; }";
	mailOptions += "\/* Webkit Elements *\/";
	mailOptions += "#top-bar { border-radius:6px 6px 0px 0px; -moz-border-radius: 6px 6px 0px 0px; -webkit-border-radius:6px 6px 0px 0px; -webkit-font-smoothing: antialiased; background-color: #7e8485; color: #e7cba3; }";
	mailOptions += "#top-bar a { font-weight: bold; color: #e7cba3; text-decoration: none;}";
	mailOptions += "#footer { border-radius:0px 0px 6px 6px; -moz-border-radius: 0px 0px 6px 6px; -webkit-border-radius:0px 0px 6px 6px; -webkit-font-smoothing: antialiased; }";
	mailOptions += "\/* Fonts and Content *\/";
	mailOptions += "body, td { font-family: HelveticaNeue, sans-serif; }";
	mailOptions += ".header-content, .footer-content-left, .footer-content-right { -webkit-text-size-adjust: none; -ms-text-size-adjust: none; }";
	mailOptions += "\/* Prevent Webkit and Windows Mobile platforms from changing default font sizes on header and footer. *\/";
	mailOptions += ".header-content { font-size: 12px; color: #e7cba3; }";
	mailOptions += ".header-content a { font-weight: bold; color: #e7cba3; text-decoration: none; }";
	mailOptions += "#headline p { color: #e7cba3; font-family: HelveticaNeue, sans-serif; font-size: 36px; text-align: center; margin-top:0px; margin-bottom:30px; }";
	mailOptions += "#headline p a { color: #e7cba3; text-decoration: none; }";
	mailOptions += ".article-title { font-size: 18px; line-height:24px; color: #9a9661; font-weight:bold; margin-top:0px; margin-bottom:18px; font-family: HelveticaNeue, sans-serif; }";
	mailOptions += ".article-title a { color: #9a9661; text-decoration: none; }";
	mailOptions += ".article-title.with-meta {margin-bottom: 0;}";
	mailOptions += ".article-meta { font-size: 13px; line-height: 20px; color: #ccc; font-weight: bold; margin-top: 0;}";
	mailOptions += ".article-content { font-size: 13px; line-height: 18px; color: #444444; margin-top: 0px; margin-bottom: 18px; font-family: HelveticaNeue, sans-serif; }";
	mailOptions += ".article-content a { color: #00707b; font-weight:bold; text-decoration:none; }";
	mailOptions += ".article-content img { max-width: 100% }";
	mailOptions += ".article-content ol, .article-content ul { margin-top:0px; margin-bottom:18px; margin-left:19px; padding:0; }";
	mailOptions += ".article-content li { font-size: 13px; line-height: 18px; color: #444444; }";
	mailOptions += ".article-content li a { color: #00707b; text-decoration:underline; }";
	mailOptions += ".article-content p {margin-bottom: 15px;}";
	mailOptions += ".footer-content-left { font-size: 12px; line-height: 15px; color: #e2e2e2; margin-top: 0px; margin-bottom: 15px; }";
	mailOptions += ".footer-content-left a { color: #e7cba3; font-weight: bold; text-decoration: none; }";
	mailOptions += ".footer-content-right { font-size: 11px; line-height: 16px; color: #e2e2e2; margin-top: 0px; margin-bottom: 15px; }";
	mailOptions += ".footer-content-right a { color: #e7cba3; font-weight: bold; text-decoration: none; }";
	mailOptions += "#footer { background-color: #000000; color: #e2e2e2; }";
	mailOptions += "#footer a { color: #e7cba3; text-decoration: none; font-weight: bold; }";
	mailOptions += "#permission-reminder { white-space: normal; }";
	mailOptions += "#street-address { color: #e7cba3; white-space: normal; }";
	mailOptions += "<\/style>";
	mailOptions += "<!--[if gte mso 9]>";
	mailOptions += "<style _tmplitem=\"2480\" >";
	mailOptions += ".article-content ol, .article-content ul {";
	mailOptions += "   margin: 0 0 0 24px;";
	mailOptions += "   padding: 0;";
	mailOptions += "   list-style-position: inside;";
	mailOptions += "}";
	mailOptions += "<\/style>";
	mailOptions += "<![endif]--><\/head><body><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"background-table\">";
	mailOptions += "	<tbody><tr>";
	mailOptions += "		<td align=\"center\" bgcolor=\"#ececec\">";
	mailOptions += "        	<table class=\"w640\" style=\"margin:0 10px;\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "            	<tbody><tr><td class=\"w640\" width=\"640\" height=\"20\"><\/td><\/tr>";
	mailOptions += "                ";
	mailOptions += "            	<tr>";
	mailOptions += "                	<td class=\"w640\" width=\"640\">";
	mailOptions += "                        <table id=\"top-bar\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" bgcolor=\"#242424\">";
	mailOptions += "    <tbody><tr>";
	mailOptions += "        <td class=\"w15\" width=\"15\"><\/td>";
	mailOptions += "        <td class=\"w325\" width=\"350\" valign=\"middle\" align=\"left\">";
	mailOptions += "            <table class=\"w325\" width=\"350\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                <tbody><tr><td class=\"w325\" width=\"350\" height=\"8\"><\/td><\/tr>";
	mailOptions += "            <\/tbody><\/table>";
	mailOptions += "            <div class=\"header-content\">Team<\/div>";
	mailOptions += "            <table class=\"w325\" width=\"350\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                <tbody><tr><td class=\"w325\" width=\"350\" height=\"8\"><\/td><\/tr>";
	mailOptions += "            <\/tbody><\/table>";
	mailOptions += "        <\/td>";
	mailOptions += "        <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "        <td class=\"w255\" width=\"255\" valign=\"middle\" align=\"right\">";
	mailOptions += "            <table class=\"w255\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                <tbody><tr><td class=\"w255\" width=\"255\" height=\"8\"><\/td><\/tr>";
	mailOptions += "            <\/tbody><\/table>";
	mailOptions += "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "    <tbody><tr>";
	mailOptions += "       ";
	mailOptions += "        ";
	mailOptions += "    <\/tr>";
	mailOptions += "<\/tbody><\/table>";
	mailOptions += "            <table class=\"w255\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                <tbody><tr><td class=\"w255\" width=\"255\" height=\"8\"><\/td><\/tr>";
	mailOptions += "            <\/tbody><\/table>";
	mailOptions += "        <\/td>";
	mailOptions += "        <td class=\"w15\" width=\"15\"><\/td>";
	mailOptions += "    <\/tr>";
	mailOptions += "<\/tbody><\/table>";
	mailOptions += "                        ";
	mailOptions += "                    <\/td>";
	mailOptions += "                <\/tr>";
	mailOptions += "                <tr>";
	mailOptions += "                <td id=\"header\" class=\"w640\" width=\"640\" align=\"center\" bgcolor=\"#242424\">";
	mailOptions += "    ";
	mailOptions += "    <table class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "        <tbody><tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580\" width=\"580\" height=\"30\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>";
	mailOptions += "        <tr>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "            <td class=\"w580\" width=\"580\">";
	mailOptions += "                <div align=\"center\" id=\"headline\">";
	mailOptions += "                    <p>";
	mailOptions += "                        <strong><singleline label=\"Title\">Booking Confirmation<\/singleline><\/strong>";
	mailOptions += "                    <\/p>";
	mailOptions += "                <\/div>";
	mailOptions += "            <\/td>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "        <\/tr>";
	mailOptions += "    <\/tbody><\/table>";
	mailOptions += "    ";
	mailOptions += "    ";
	mailOptions += "<\/td>";
	mailOptions += "                <\/tr>";
	mailOptions += "                ";
	mailOptions += "                <tr><td class=\"w640\" width=\"640\" height=\"30\" bgcolor=\"#ffffff\"><\/td><\/tr>";
	mailOptions += "                <tr id=\"simple-content-row\"><td class=\"w640\" width=\"640\" bgcolor=\"#ffffff\">";
	mailOptions += "    <table align=\"left\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "        <tbody><tr>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "            <td class=\"w580\" width=\"580\">";
	mailOptions += "                <repeater>";
	mailOptions += "                    ";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Booking Id : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingId+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "                    <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Pickup Address : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.pickup+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">DropOff Address : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.dropoff+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Date & Time : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.pickupdatetime+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "                               ";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">No Of Passengers : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.passengers+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Name : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.name+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Email Id : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.emailid+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"left\" class=\"article-title\"><singleline label=\"Title\">Phone Number : <\/singleline><\/p>";
	mailOptions += "                                    <div align=\"left\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">"+bookingDetails.phone+"<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "					";
	mailOptions += "					 <layout label=\"Text only\">";
	mailOptions += "                        <table class=\"w580\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
	mailOptions += "                            <tbody><tr>";
	mailOptions += "                                <td class=\"w580\" width=\"580\">";
	mailOptions += "                                    <p align=\"right\" class=\"article-title\" style=\"color:black;\"><singleline label=\"Title\">Enjoy Your Ride!!!<\/singleline><\/p>";
	mailOptions += "                                    <div align=\"right\" class=\"article-content\">";
	mailOptions += "                                        <multiline label=\"Description\">Thanks for your Booking<\/multiline>";
	mailOptions += "                                    <\/div>";
	mailOptions += "                                <\/td>";
	mailOptions += "                            <\/tr>";
	mailOptions += "                            <tr><td class=\"w580\" width=\"580\" height=\"10\"><\/td><\/tr>";
	mailOptions += "                        <\/tbody><\/table>";
	mailOptions += "                    <\/layout>";
	mailOptions += "                   ";
	mailOptions += "                <\/repeater>";
	mailOptions += "            <\/td>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "        <\/tr>";
	mailOptions += "    <\/tbody><\/table>";
	mailOptions += "<\/td><\/tr>";
	mailOptions += "                <tr><td class=\"w640\" width=\"640\" height=\"15\" bgcolor=\"#ffffff\"><\/td><\/tr>";
	mailOptions += "                ";
	mailOptions += "                <tr>";
	mailOptions += "                <td class=\"w640\" width=\"640\">";
	mailOptions += "    <table id=\"footer\" class=\"w640\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" bgcolor=\"#000000\">";
	mailOptions += "        <tbody><tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580 h0\" width=\"360\" height=\"30\"><\/td><td class=\"w0\" width=\"60\"><\/td><td class=\"w0\" width=\"160\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>";
	mailOptions += "        <tr>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "            <td class=\"w580\" width=\"360\" valign=\"top\">";
	mailOptions += "            <span class=\"hide\"><p id=\"permission-reminder\" align=\"left\" class=\"footer-content-left\"><\/p><\/span>";
	mailOptions += "            <p align=\"left\" class=\"footer-content-left\">Team Name<\/p>";
	mailOptions += "            <\/td>";
	mailOptions += "            <td class=\"hide w0\" width=\"60\"><\/td>";
	mailOptions += "            <td class=\"hide w0\" width=\"160\" valign=\"top\">";
	mailOptions += "            <p id=\"street-address\" align=\"right\" class=\"footer-content-right\"><\/p>";
	mailOptions += "            <\/td>";
	mailOptions += "            <td class=\"w30\" width=\"30\"><\/td>";
	mailOptions += "        <\/tr>";
	mailOptions += "        <tr><td class=\"w30\" width=\"30\"><\/td><td class=\"w580 h0\" width=\"360\" height=\"15\"><\/td><td class=\"w0\" width=\"60\"><\/td><td class=\"w0\" width=\"160\"><\/td><td class=\"w30\" width=\"30\"><\/td><\/tr>";
	mailOptions += "    <\/tbody><\/table>";
	mailOptions += "<\/td>";
	mailOptions += "                <\/tr>";
	mailOptions += "                <tr><td class=\"w640\" width=\"640\" height=\"60\"><\/td><\/tr>";
	mailOptions += "            <\/tbody><\/table>";
	mailOptions += "        <\/td>";
	mailOptions += "	<\/tr>";
	mailOptions += "<\/tbody><\/table><\/body><\/html>";
	mailOptions += "";

	
    return mailOptions;
};
